library(igraph)
library(RedeR)
g <- graph_from_data_frame(pathway2dataframe("hsa00010"))
cut <- min_cut(g, value.only=FALSE)
names(cut$partition1)
names(cut$partition2)
rdp <- RedPort()
calld(rdp)
resetd(rdp)
addGraph(rdp, g)
selectNodes(rdp, names(cut$partition2))
